### ISSUE TITLE
15 Broad story

### ISSUE THREAD

**Issue by reichs** [bdon/80s.nyc#2]
The story says it is a picture of the NY Stock Exchange.  Unfortunately, the Exchange is across the street from 15 Broad Street (23 Wall Street) at 11 Wall Street.  

For a bit more history on the 15 Broad Street building, you might want to link to https://en.wikipedia.org/wiki/23_Wall_Street (and the 1920 bombing).

**Comment by bdon** [comment]
Fixed, thank you for the correction.
